### ISSUE TITLE
Implement bbcodes

### ISSUE THREAD

**Issue by aeron005** [64Digits/sixtyfour#6]
Extend bbcode formatter, add codes supported from old site.

Simple tags:

- [x] 'b'
- [x] 'i'
- [x] 'u'
- [ ] 'li'
- [x] '*' (Same as li tag)
- [ ] 'ul'
- [ ] 'ol'
- [x] 'sub'
- [x] 'sup'
- [ ] 'h1'
- [ ] 'h2'
- [ ] 'h3'
- [ ] 'h4'
- [ ] 'h5'
- [ ] 'h6'
- [ ] 'tt'

Potentially more complex:

- [x] 'hr'
- [ ] 'br'
- [ ] 'img'
- [x] 's'
- [x] 'list'
- [x] 'center'
- [ ] 'right'
- [ ] 'o'
- [ ] 'u2'
- [ ] 'rev'
- [ ] 'em'
- [ ] 'ln'
- [x] 'color'
- [ ] 'font'
- [ ] 'size'
- [x] 'url'
- [x] 'quote'
- [x] 'code'
- [ ] 'tnail'
- [ ] 'hide'
- [ ] 'show'
- [ ] 'nsfw'
- [ ] 'shh'
- [ ] 'blind'
- [ ] 'user'
- [ ] 'profile'
- [ ] 'h5audio'
- [ ] 'h5video'
- [ ] 'audio'
- [ ] 'youtube'
- [ ] 'youtubehd'
- [ ] 'youtubeaudio'
- [ ] 'vimeo'
- [ ] 'soundcloud'
- [ ] 'flash'
- [ ] 'paypal'
- [ ] 'theusertag'
- [ ] 'markdown'
- [ ] 'rand'

**Comment by 64Mega** [comment]
The BBCode package supports several of these tags already by default, I've marked off the ones that are already implemented. A summary:
b, i, u, s, hr, sub, sup, list (Renders as ul with * tag producing li children), quote, code, center, color and url.
